### ISSUE TITLE
Why can't "IDEAS" or "FastBuildings" be found?

### ISSUE THREAD

**Issue by tbeu** [impact/search#14]
Why does a serach for "ideas" or "IDEAS" give no hits though it is listed on mo-3rd-party? Is it due to the missing releases?

**Comment by xogeny** [comment]
Easy, because it is not in the index.  Now, you might then ask...why isn't in the index?  Looking at the repository, it doesn't have a single tag that conforms to the specifications required by impact (*e.g.,* `v0.3.0`).

**Comment by tbeu** [comment]
Hm, MessagePack shows a version 0.1.0 though there is not such a release at https://github.com/modelica-3rdparty/msgpack-modelica/releases. There only is v0.1 which is not according to semver.

**Comment by xogeny** [comment]
If something is close to semver, we "normalize" it.  But IDEAS doesn't have anything close to semver, IIRC.

**Comment by tbeu** [comment]
Right.
