### ISSUE TITLE
Combine library page with search page

### ISSUE THREAD

**Issue by dietmarw** [impact/search#4]
When thinking of moving the generation of the [current library page](http://impact.github.io/libraries.html) I wondered if we perhaps should not combine that page with the search page. 

What I have in mind is a page that by default displays all the libraries in the groups: 
 * MA libs standard conform
 * MA libs
 * 3rd party libs

and if the user types something in the search field it basically acts as a **filter** and **only** displays libraries matching the filter criteria but still with the group in which they reside.

**Comment by xogeny** [comment]
So would you prefer that, by default, it lists the all libraries when the search field is empty?

**Comment by xogeny** [comment]
Since modelica.org contains a complete list, the decision was to leave this as is.
